---
title: "Final Project"
date: "2025-01-27"
format: 
  html:
    embed-resources: true
    code-tools: true
    code-summary: "Code"
draft: false
---

## Overview

This course culminates with a project in which you will explore a dataset or dimension reduction technique of your choice. Examples of appropriate projects include the following:

-   Present a dimension reduction method not covered in class. You should introduce the key technical details of your algorithm and demonstrate your selected approach on a real dataset.
-   Provide a tutorial introducing a dimension reduction method covered in this course **at a level suitable for junior/senior undergraduate students or graduate students**. You should apply your method to a real-world dataset, review your selected approach, explore different options and parameter configurations, and discuss strengths, weaknesses, and potential pitfalls of your approach.
-   Compare two or more dimension reduction methods covered in this course using a real-world dataset or simulated data. Review the technical details of your selected approaches, discuss differences in their performance, and offer practical advice on choosing a dimension reduction technique in your chosen setting.
-   Extend an existing dimension reduction method or review a theoretical result/paper not discussed in class.

You may work in groups of two students or three students. All members of a group are responsible for contributing to all parts of the project. You may work independently on your project with the instructor's approval. **If you would like to work on your own, you must meet with the instructor before submitting your project proposal.** During the semester, you will submit a written project proposal which must be approved by the instructor. At the end of the semester, you will deliver a short oral presentation on your project and submit a written report of your results as well as a brief reflection and self-evaluation.

Your project will be evaluated based on the following aspects of your work:

-   **Technical Details**: clearly and correctly presenting the technical details of your selected dimension reduction algorithm(s) and dataset(s). In other words, a peer who hasn't taken this class should be able to understand how your method works based on your explanation.
-   **Application**: appropriately applying your selected method(s) to real or simulated data, producing effective visualizations, and correctly interpreting the results.
-   **Exposition and Presentation**: producing a written report and delivering your oral presentation.

This project is intentionally open-ended: there are no predetermined right answers. Exceptional projects will demonstrate mastery of the course material and involve more than a superficial review of a method covered in class or application using a toy dataset.

## Part One: Project Proposal (10 points), due 3/28

You will submit a 1-2 page project proposal with the following information:

-   Your project title
-   A brief description of your proposed project with clearly stated goals
-   A description of any dataset you plan to use (with links/references)
-   A description of any dimension reduction methods you plan to use
-   A list of papers/references that you plan to use
-   Any questions you have for the instructor

You are encouraged to meet with the instructor to discuss potential project topics and datasets **before** beginning your project proposal. If you wish to use a dataset discussed in class, you should obtain instructor approval.

## Part Two: Final Report (70 points), due 5/12

You will also submit a written report that clearly explains your project and findings. The structure of your report will depend on your selected project topic, but a broad outline could look like the following:

-   **Introduction**: your motivating problem and outline of your research questions and results
-   **Methods**: technical description and background for your dimension reduction method(s)
-   **Data**: description of your selected dataset(s)
-   **Application and results**: explanation of how you applied your method to real/simulated data and the ensuing results or visualizations
-   **Discussion**: Summary of your findings and questions for future research

There is no explicit page limit/requirement, but a report of 5-7 single-spaced pages, not including figures/references, should be sufficient for most projects. The target audience of your report is a classmate who may not be familiar with your selected datasets or dimension reduction algorithms.

## Part Three: Class Presentation (15 points), slides due 5/12

At the end of the semester, you will deliver a brief lightning talk in class. You should rehearse your presentation in advance and it should include:

-   An introduction to your research topic and description of your project (which methods or datasets are you using?)
-   Description of any applications/simulations you performed and the results
-   Summary of your findings and questions for future research

## Part Four: Reflection and Self-evaluation (5 points), due 5/12

You will complete a 1-2 page reflection and self-evaluation on your work for this final project and course. Briefly answer the following questions:

1.  If you worked with a group, what were your specific responsibilities for the project proposal, report, and presentation?
2.  Describe at least one aspect of your work for this class of which you are proud. Are there any ways in which you grew this semester?
3.  Describe at least one aspect of your work which you could have improved.
