---
title: "MATH250: Mathematical Methods for Data Visualization"
format: html
draft: false
---

::: column-screen-inset-right
| Week | Date   | Topic                                         | Readings                                 |                         Slides                         |                   HW                   |
|:----------:|------------|-------------|:-----------|:----------:|:----------:|
|  1   | M 1/27 | Overview: Data as representation              |                                          | [Slides 01](slides/01_intro.pdf){.label .label-purple} | [HW 01](hw/hw1.pdf){.label .label-red} |
|      | W 1/29 | Highlights of linear algebra                  | Strang I.1 and I.2, Murphy Ch. 7         | [Notes 02](slides/02_notes.pdf){.label .label-purple}  |                                        |
|  2   | M 1/3  | Highlights of linear algebra                  | Strang I.3 and I.4                       | [Notes 03](slides/03_notes.pdf){.label .label-purple}  |                                        |
|      | W 1/5  | *Class canceled*                              |                                          |                                                        |                                        |
|  3   | M 2/10 | Highlights of linear algebra                  | Strang I.5 and I.6                       |  [Notes 04](slides/04_notes.pdf){.label .label-purple}                                                       |  [HW 02](hw/hw2.pdf){.label .label-red} [Lab](labs/matrix-algebra-lab.html){.label .label-red}                                      |
|      | W 2/12 | Highlights of linear algebra                  | Strang I.7                               | [Notes 05](slides/05_notes.pdf){.label .label-purple}                                                       |                                        | 
|  4   | M 2/17 | Singular value decomposition                  | Strang I.8 and I.9                       |  [Notes 06](slides/06_notes.pdf){.label .label-purple}                                                               |                                        |
|      | W 2/19 | Singular value decomposition                  |                                          |    [Notes 07](slides/07_notes.pdf){.label .label-purple}                                                      |     [HW 03](hw/hw3.pdf){.label .label-red} [Lab](labs/svd-pca-lab/03_lab.html){.label .label-red}                                     |
|  5   | M 2/24 | Singular value decomposition                 | Strang I.10, I.11, and I.12, Murphy 20.1 |   [Notes 08](slides/08_notes.pdf){.label .label-purple}                                                      |                                        |
|      | W 2/26 | Principal components analysis                 |                                          |    [Notes 09](slides/09_notes.pdf){.label .label-purple}                                                       |                                        |
|  6   | M 3/3  | Principal components analysis                 | Strang II.1 and II.2                     |        [Slides 10](slides/10_PCA.pdf){.label .label-purple}                                                   |                                        |
|      | W 3/5  | Linear systems and least squares              |                                          |                                                        |                                        |
|  7   | M 3/10 | EXAM I                                        |                                          |                                                        |                                        |
|      | W 3/12 | Linear systems and least squares | Murphy 3.1, 3.2, 20.2                    |                                                        | [HW 04](hw/hw4.pdf){.label .label-red} [Lab](labs/linear-systems/04_lab.html){.label .label-red}                                       |
|  8   | M 3/17 | Dimension reduction and statistical inference | Murphy 3.1, 3.2, 20.2                    |  [Notes 11](slides/11_notes.pdf){.label .label-purple}                                                       |                                        |
|      | W 3/19 | Dimension reduction and statistical inference |                                          |                                                        |                                        |
|  9   | M 3/24 | Visualization                                 | Murphy 20.4                              |                                                        |                                        |
|      | W 3/26 | Manifold learning                             | Murphy 20.3 and 20.4                     |                                                        |                                        |
|  10  | M 3/31 | *Cesar Chavez Day - No class*                 |                                          |                                                        |                                        |
|      | W 4/2  | *Spring Break - No class*                     |                                          |                                                        |                                        |
|  11  | M 4/7  | Manifold learning                             | Murphy 20.3 and 20.4                     |                                                        |                                        |
|      | W 4/9  | Manifold learning                             |                                          |                                                        |                                        |
|  12  | M 4/14 | Classification                                | Murphy Ch. 9                             |                                                        |                                        |
|      | W 4/16 | Classification                                |                                          |                                                        |                                        |
|  13  | M 4/21 | Clustering                                    | Murphy 21.5                              |                                                        |                                        |
|      | W 4/23 | Text mining                                   |                                          |                                                        |                                        |
|  14  | M 4/28 | Embeddings and LLMs                           | Murphy 20.5                              |                                                        |                                        |
|      | W 4/30 | Review                                        |                                          |                                                        |                                        |
|  15  | M 5/5  | EXAM II                                       |                                          |                                                        |                                        |
|      | W 5/7  | Final presentations                           |                                          |                                                        |                                        |
|  16  | M 5/12 | Final presentations                           |                                          |                                                        |                                        |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides |                    AE                    | Labs | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋 [Lab 01](hello){.label .label-purple} |  ✍️  |     |      |         |
