---
title: "License"
format: html
draft: false
---

These course materials are licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

This is a brief summary of the license, which can be found [here](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode). Official translations of this license are available in [other languages](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode#languages).

You are free to:

-   Share — copy and redistribute the material in any medium or format
-   Adapt — remix, transform, and build upon the material

Under the following terms:

-   Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
-   NonCommercial — You may not use the material for commercial purposes.
-   ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
-   No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
