---
title: "Resources"
format: html
draft: false
---

# Helpful readings

-   [The Fundamental Theorem of Linear Algebra by Gilbert Strang](https://www.jstor.org/stable/2324660)

# Helpful courses and videos

-   [Matrix Methods In Data Analysis, Signal Processing, And Machine Learning at MIT](https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/)
-   [Mathematical Foundations of Machine Learning at UChicago](https://willett.psd.uchicago.edu/teaching/mathematical-foundations-of-machine-learning-fall-2021/)
-   [Data Driven Science and Engineering at UW](https://www.databookuw.com)
-   [Steve Brunton's SVD videos](https://www.youtube.com/playlist?list=PLMrJAkhIeNNSVjnsviglFoY2nXildDCcv)
-   [3blue1brown's Essence of Linear Algebra videos](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
-   [Data Visualization with R at Georgia State University](https://datavizf23.classes.andrewheiss.com)
-   [Mathematics for Deep Learning at University of Tübingen](https://uni-tuebingen.de/de/241678)

# High-dimensional datasets

# Examples of data analyses/visualizations

-   [Advanced data visualizations by Tanya Shapiro](https://github.com/tashapiro/tanya-data-viz): Going above and beyond the basic capabilities of R visualizations
-   [Data visualization with NFL data by Bradley J Congelio](https://bradcongelio.com/nfl-analytics-with-r-book/04-nfl-analytics-visualization.html): Great example of using R to generate advanced data visualizations about the NFL.
-   [Exploring college major and income: a live data analysis in R by David Robinson](http://varianceexplained.org/r/tidy-tuesday-college-major/): Video example of a data analysis, in real time.

# Datasets

-   [CDC](https://www.cdc.gov/datastatistics/)
-   [Data.gov](https://www.data.gov/)
-   [Data is Plural](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)
-   [Federal Reserve Economic Data](https://fred.stlouisfed.org)
-   [General Social Survey](https://gss.norc.org/)
-   [Google Dataset Search](https://datasetsearch.research.google.com/)
-   [Harvard Dataverse](https://dataverse.harvard.edu/)
-   [International Monetary Fund](https://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42&sId=1479329328660)
-   [IPUMS survey data from around the world](https://ipums.org/)
-   [Our World In Data](https://ourworldindata.org)
-   [Pew Research](https://www.pewresearch.org/download-datasets/)
-   [PRISM Data Archive Project](https://www.icpsr.umich.edu/icpsrweb/content/ICPSR/fenway.html)
-   [San Francisco Open Data](https://data.sfgov.org/)
-   [San Jose Open Data](https://data.sanjoseca.gov)
-   [Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/)
-   [The National Bureau of Economic Research](https://www.nber.org/research/data?page=1&perPage=50)
-   [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master)
-   [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php)
-   [UNICEF Data](https://data.unicef.org/)
-   [United Nations Data](http://data.un.org/)
-   [United Nations Statistics Division](https://unstats.un.org/UNSDWebsite/)
-   [US Census Data](https://www.census.gov/data.html)
-   [US Government Data](https://sctyner.github.io/static/presentations/Misc/GraphicsGroupISU/2018-11-16-us-govt-data.html)
-   [World Bank Data](https://datacatalog.worldbank.org/home)
-   [Youth Risk Behavior Surveillance System (YRBSS)](https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-Youth-Risk-Behavior-Surveillance-System-YRBSS/q6p7-56au)
