---
title: "Syllabus"
format: html
draft: false
---

## Course information

+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| **Instructor**   | Peter A. Gao                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| **Lectures**     | Weekly on Monday and Wednesday, 9-10:15am in MH234                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| **Office Hours** | Monday and Wednesday, 10:30-11:30am in MH426 or email for an appointment                                                                                                                                                                                                                                                                                                                                                                                                                                                       |      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| **Email**        | peter.gao \[at sjsu\]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |      |
|                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |      |
|                  | *Email or the course discussion board is the best way to reach me. Email should be used for administrative/logistics issues and the discussion board should be used for questions on course material or homework. Questions about the homework submitted by email will generally be redirected to the discussion board. I will make every effort to respond to emails/discussion posts within a day, but please feel free to send me a reminder after 48 hours have passed. Please include \[MATH 250\] in your subject line.* |      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+

## Course learning outcomes

This course provides an introduction to key mathematical concepts for multivariate and high-dimensional data analysis. In particular, this course focuses on using matrix computation and dimension reduction techniques to visualize and draw conclusions from high-dimensional data. Mathematical topics covered include linear algebra concepts and matrix decompositions that are used for data analysis and visualization (ex. factor analysis, principal components analysis, canonical correlation analysis, multidimensional scaling) and for unsupervised and supervised machine learning methods (ex. spectral clustering, linear discriminant analysis). These ideas will be applied to visualize and analyze real-world examples of high-dimensional datasets. The programming language R will be used to implement the methods and algorithms discussed in class.

Upon successful completion of this course, students will be able to:

-   Use software to carry out various linear algebra operations

-   Plot and visualize data of various types in software and create publication-quality graphics

-   Perform matrix singular value decomposition and other advanced linear algebra operations and interpret their results in the context of data analysis

-   Apply dimensionality reduction to high dimensional data and visualize them in low dimensions

-   Develop a basic understanding of the machine learning task of clustering

## Materials

The primary texts for the course will be the lecture slides and the following books (available via [Library Course Reserves](https://sjsu.instructure.com/courses/1581919/external_tools/71748)):

-   Strang, G. (2019). Linear Algebra and Learning From Data. Available for free via [Library Course Reserves](https://sjsu.instructure.com/courses/1581919/external_tools/71748).

-   Murphy, K. P. (2022). Probabilistic Machine Learning: An Introduction. Available for free via [Library Course Reserves](https://sjsu.instructure.com/courses/1581919/external_tools/71748).

-   Murphy, K. P. (2023). Probabilistic Machine Learning: Advanced Topics. Available for free via [Library Course Reserves](https://sjsu.instructure.com/courses/1581919/external_tools/71748).

The following texts may be also be helpful:

-   Fessler, J.A. and Nadakuditi, R. R. (2024). Linear Algebra for Data Science, Machine Learning, and Signal Processing.

-   Baker, J. D. (2024). Applied Multivariate Statistics in R. Available for free [here](https://uw.pressbooks.pub/appliedmultivariatestatistics/).

-   Healy, K. (2019). Data Visualization: A Practical Introduction. Draft version available [here](https://socviz.co/).

-   Strang, G. (2023). Introduction to Linear Algebra, Sixth Edition.

The main way we will interact with R is through the software RStudio, both of which can be downloaded and installed for free. The students will be required to have access to a computer with R and RStudio. The computer lab in MacQuarrie Hall 221 contains computers with all of the software that will be used during the semester. All of the coursework may be completed on a personal computer and the software is freely available to students.

## Course requirements and grading

-   **Homework**: Throughout the semester, you complete homework assignments. You will typically have two weeks for a homework assignment. At the end of the quarter, your lowest lab grade will be dropped.

-   **Exams**: There will be two exams during the semester. Practice questions will be provided in advance of the exams. There will be no make-up exams.

-   **Final project:** During the semester, you will complete a class project that requires you to apply the data manipulation, visualization, and analysis skills covered in this course to a real-world dataset of your choice. Throughout the semester, you will submit a project proposal and multiple checkpoint assignments that will help you to prepare a final report and presentation.

-   **Late Work**: In general, the late policy is as follows: Any assignment that is received late but less than 24 hours late will receive a grade penalty of 25%. Any assignment that is received 24 to 48 hours late will receive a grade penalty of 50%. Assignments will not be accepted more than 48 hours late. Extensions for academic purposes (ex. conference presentation or job interview) or extreme circumstances (ex. illness, emergency) will generally be granted. If you would like to request an extension, please do your best to email me at least 24 hours before an assignment is due, along with the reason. 

Success in this course is based on the expectation that students will spend, for each unit of credit, a minimum of 45 hours over the length of the course (normally three hours per unit per week) for instruction, preparation/studying, or course related activities, including but not limited to internships, labs, and clinical practica. Other course structures will have equivalent workload expectations as described in the syllabus.

### Grading scale

Your final grade will be calculated as follows:

-   25%: Homework

-   25%: Exam 1 

-   25%: Exam 2

-   25%: Final project

There may be the opportunity for extra credit.

| Letter Grade | Raw Percentage |
|--------------|----------------|
| A plus       | 96 to 100%     |
| A            | 93 to 95%      |
| A minus      | 90 to 92%      |
| B plus       | 86 to 89%      |
| B            | 83 to 85%      |
| B minus      | 80 to 82%      |
| C plus       | 76 to 79%      |
| C            | 73 to 75%      |
| C minus      | 70 to 72%      |
| D plus       | 66 to 69%      |
| D            | 63 to 65%      |
| D minus      | 60 to 62%      |
| F            | 0 to 60%       |

## Course Schedule

The updated course schedule is available on the course homepage [here](math250-s24.github.io).

## Policies

### Feedback

I encourage and appreciate your feedback throughout the quarter. You are welcome to provide feedback on any aspect of the course at any time via email or in person. If you would prefer to do so confidentially, you can do so through the anonymous feedback form on this website.

### Collaboration

On most assignments, collaboration is allowed and encouraged. You may discuss problems, approaches, and solutions with your classmates. Acceptable collaboration is limited to your classmates in this course and you must clearly include on any collaborative work the name(s) of anyone with whom you worked. Additionally, all submitted work must be your own; you should not submit code or answers copied from any resource including your classmates. Plagiarism and cheating is easy to detect and can lead to serious negative consequences for you. If you have any questions regarding this policy, please ask for clarification.

### Online resources

Students may use external online resources including discussion forums (ex. StackOverflow) large language model-based chatbots (ex. ChatGPT) **as aids for learning and understanding course material**. However, submitting code or answers for course labs, assignments, exams, and projects obtained using external resources like StackOverflow or ChatGPT is not permitted. **When external resources are consulted for an assignment, they must be cited clearly at the top of your submission.**

### Discussion

You are encouraged to participate on the discussion forum by posting questions about assignments and answering questions from other students. Posts may not include substantial amounts of code that can be used for a solution to any problem, but may include code snippets within reason. Participation, in the form of both questions and answers, can earn you up to 2% extra credit for your final grade. Posts will be evaluated based on how substantive and helpful they are to the class.

### University policies

Per University Policy S16-9, relevant university policy concerning all courses, such as student responsibilities, academic integrity, accommodations, dropping and adding, consent for recording of class, etc. and available student services (e.g. learning assistance, counseling, and other resources) are listed on Syllabus Information web page ([link](https://www.sjsu.edu/curriculum/courses/syllabus-info.php)). Make sure to visit this page to review and be aware of these university policies and resources.
