---
title: "Singular Value Decomposition and Principal Components Analysis"
author: "YOUR NAME HERE"
date: ""
format: 
  html:
    embed-resources: true
    code-tools: true
    code-summary: "Code"
---
Your solutions should include both R code and any output requested. You may organize your solutions using an R Markdown document or in a pdf/docx format. If you use this .Rmd as your starting template, please remove all instructions, details, and requirements. 

You may collaborate with your classmates and consult external resources, but you should write and submit your own answer. **Any classmates with whom you collaborate should be credited at the top of your submission. Similarly, if you consult any external references, you should cite them clearly and explicitly.**

# Singular Value Decomposition

For this part, you will be exploring U.S. Congress voting data from  [voteview.com](https://www.voteview.com). Your goal is to examine the partisanship of U.S. Congress using the singular value decomposition. I **strongly** recommend saving a version of the unprocessed .csv files on your machine so you will be able to work offline. The data are available at:
  * [117th House of Representatives](https://github.com/math250-s24/math250-s24.github.io/raw/main/labs/svd-pca-lab/H117_votes_clean.csv)
  * [117th Senate](https://github.com/math250-s24/math250-s24.github.io/raw/main/labs/svd-pca-lab/S117_votes_clean.csv)
  
* `rc` columns stand for roll calls. Each vote has it's own roll call. The code is as follows:
  * `1`: "Yea" vote
  * `-1`: "Nay" vote
  * `0`: Abstain or not present during roll call

1. Read the Introduction, Voting Patterns, and Conclusions sections of [this research article (Porter et al., 2005)](HouseOfRepresentatives.pdf). Based on the authors' explanation, what do the left singular vectors of their analysis represent? What do the right singular vectors represent?
2. What interpretations do Porter et al. assign to their first two left singular vectors? Do you think these are reasonable interpretations? Why or why not?
3. Load the 117th House data into R and use the `svd` function to perform singular value decomposition on the votes data. Plot a scatter plot using your first two left singular vectors, using color to indicate political party affiliation. What interpretations, if any, can you assign to the first two left singular vectors? How do your results compare with Porter et al.'s results?
4. What proportion of variance in the data do your first two left singular vectors account for? What does this indicate?
5. Repeat this analysis for the 117th Senate data. Compare and contrast your results for the two datasets.

# Principal components analysis

For this portion of the lab, you may select any dataset that interests you with which to carry out a principal components analysis. 

1. Choose a dataset and provide a brief description of your selected dataset. What does each row and column represent? You should choose a dataset with enough numerical variables to make PCA or some other dimension reduction approach appropriate (ex > 5). 
2. Carry out a principal components analysis using your dataset. You may use the `prcomp` function in R or compute the principal components by hand. 
3. Provide a biplot of the first two principal components and their variable loadings and comment on your findings. Are the first two principal components interpretable? What are the limitations of using principal components analysis with your data?